name: Merge any project's release branch to develop
run-name: ${{ github.actor }} has merged a PR in ${{ github.base_ref }}
on:
  pull_request:
    types:
      - closed
    branches:
      - '*/*.*.*'

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Merge release -> main
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: main
          message: Merge ${{ github.base_ref }} branch into main
          github_token: ${{ secrets.MY_TOKEN }}
